"""Phonecalls

Revision ID: 226a2952d6a0
Revises: 3e03d4612646
Create Date: 2023-12-19 12:02:32.577526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226a2952d6a0'
down_revision = '3e03d4612646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caller', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_call')
    # ### end Alembic commands ###
